# Generated by Django 4.2.3 on 2023-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Article content'),
        ),
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/206/206906.png', upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='https://contenthub-static.grammarly.com/blog/wp-content/uploads/2022/08/BMD-3398-760x400.png', upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Author bio'),
        ),
    ]
