# Generated by Django 4.2.3 on 2023-08-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_description_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='article_image',
        ),
        migrations.AddField(
            model_name='article',
            name='author_bio',
            field=models.TextField(default='Author bio'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_image',
            field=models.TextField(default='https://cdn-icons-png.flaticon.com/512/206/206906.png'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
